## Today Agenda
- Decision tree regressor
- Random Forest Model

### Decision Tree Regressor 
- Target --> Continous
- Accuracy --> Evaluation Metrics
    - Mean Square Error(MSE) or R2_Score

In [1]:
import numpy as np
import pandas as pd

In [23]:
data = pd.read_csv('https://raw.githubusercontent.com/nagamounika5/Datasets/master/headbrain.csv')

In [24]:
data.head()

Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0       1          1             4512                 1530
1       1          1             3738                 1297
2       1          1             4261                 1335
3       1          1             3777                 1282
4       1          1             4177                 1590

In [4]:
data.shape

(237, 4)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gender               237 non-null    int64
 1   Age Range            237 non-null    int64
 2   Head Size(cm^3)      237 non-null    int64
 3   Brain Weight(grams)  237 non-null    int64
dtypes: int64(4)
memory usage: 7.5 KB


In [6]:
data.describe()

Gender   Age Range  Head Size(cm^3)  Brain Weight(grams)
count  237.000000  237.000000       237.000000           237.000000
mean     1.434599    1.535865      3633.991561          1282.873418
std      0.496753    0.499768       365.261422           120.340446
min      1.000000    1.000000      2720.000000           955.000000
25%      1.000000    1.000000      3389.000000          1207.000000
50%      1.000000    2.000000      3614.000000          1280.000000
75%      2.000000    2.000000      3876.000000          1350.000000
max      2.000000    2.000000      4747.000000          1635.000000

In [8]:
data.isnull().sum()

Gender                 0
Age Range              0
Head Size(cm^3)        0
Brain Weight(grams)    0
dtype: int64

In [25]:
x = data.drop(['Brain Weight(grams)'], axis = 'columns')
y = data[['Brain Weight(grams)']]

In [26]:
x.head()

Gender  Age Range  Head Size(cm^3)
0       1          1             4512
1       1          1             3738
2       1          1             4261
3       1          1             3777
4       1          1             4177

In [27]:
y.head()

Brain Weight(grams)
0                 1530
1                 1297
2                 1335
3                 1282
4                 1590

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(x,y,test_size=0.2, random_state = 45)

In [29]:
print(X_train.shape)
print(y_train.shape)

(189, 3)
(189, 1)


In [30]:
print(X_test.shape)
print(y_test.shape)

(48, 3)
(48, 1)


In [31]:
## Apply decision tree model
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()

In [32]:
dtr.fit(X_train,y_train)

DecisionTreeRegressor()

In [33]:
y_pred = dtr.predict(X_test)
y_pred

array([1255. , 1310. , 1279. , 1250. , 1060. , 1375. , 1135. , 1430. ,
       1340. , 1165. , 1346. , 1296. , 1208. , 1220. , 1280. , 1565. ,
       1270. , 1350. , 1312. , 1235. , 1400. , 1340. , 1425. , 1270. ,
       1220. , 1150. ,  955. , 1220. , 1432. , 1260. , 1105. ,  955. ,
       1355. , 1180. , 1405. , 1380. , 1400. , 1440. , 1127. , 1330. ,
       1220. , 1425. , 1422.5, 1375. , 1250. , 1415. , 1316. , 1375. ])

In [34]:
X_test.head(3)

Gender  Age Range  Head Size(cm^3)
177       2          1             3561
50        1          1             3891
216       2          2             3246

In [35]:
y_test.head(3)

Brain Weight(grams)
177                 1127
50                  1224
216                 1180

In [36]:
dtr.predict([[2,1,3561]])

array([1255.])

In [37]:
dtr.predict([[1,1,3891]])

array([1310.])

In [38]:
from sklearn.metrics import r2_score
dtr.score(X_train,y_train)

0.9806967462761748

### Task: Take any data set from kaggle.com and Apply Decision Tree Regressor model